trigger: 
 - main

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'todo-webapp-golang'
- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'cloud-tank'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'cloud-tank_todo-webapp-golang'
    cliProjectName: 'todo-webapp-golang'
    cliSources: '.'
- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop